### PR TITLE
Improved testing for example inputs

### PR DESCRIPTION
**Pull request by TechSupportz**
This template is really nice but I found it a little annoying to keep changing my `input.txt` file between the actual input and the sample inputs so I decided to make a few changes to make it a little easier. Felt that this would be useful to others using this template as well! (#2)

## Changes made
* When initialising a new day, 2 new files get created
  * `example-1.txt`
  * `example-2.txt`
* When running `pnpm t` these 2 files are utilised as the inputs. The resulting values are then compared with their respective expected solution variables.
  * `example-1.txt` inputted into `first()` and returned value is compared with `expectedFirstSolution`

### CODE REVIEW

**Comment by edge33** [comment]
This is a brilliant change, thanks for taking time doing it and contributing.

I found it a bit confusing to have several example files in a day folder but just using the `input.txt` file for actual input. I believe it would be more straightforward to have the test files named something like `example-test-1` and `example-test-2` so it stands out immediately that these files are used in the tests, what do you think?

**Comment by TechSupportz** [comment]
That sounds good! Let me make the changes. Glad you found this change useful!

**Comment by edge33** [comment]
Brilliant we are ready to merge, before doing it, you can add your name and link to the contributors section of the readme file :)

**Comment by perenstrom** [comment]
Added these changes to my local fork, works a charm! Thanks a lot @TechSupportz

**Comment by edge33** [comment]
Merged, thansk again for contributing

**Pull request merged**
